version: "3.9"
services:
  db:
    image: postgres:15
    container_name: comics_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comicsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata: